[project]
name = "stock-market"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "sqlalchemy>=2.0",
  "yfinance",
  "tradingview-ta",
  "python-telegram-bot",
  "python-dotenv",
  "pandas",
  "numpy",
  "requests",
  "tqdm>=4.68.3",
  "pyarrow>=24.0.0",
  "matplotlib>=3.11.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
